export const UPLOAD_TEXT = {
  cancel: "انصراف",
  categories: "دسته‌بندی‌ها",
  categoryError: "خطا در دریافت دسته‌بندی‌ها",
  categoryLoading: "در حال بارگذاری...",
  chooseCategory: "انتخاب دسته‌بندی",
  chooseChannel: "انتخاب کانال",
  coverRequired: "تصویر کاور (اجباری)",
  description: "توضیحات",
  descriptionPlaceholder: "توضیحات ویدیو را وارد کنید (اختیاری)",
  enterVideoUrl: "لطفاً لینک ویدیو را وارد کنید.",
  fileReady: "آپلود ویدیو کامل شده و آماده انتشار است.",
  fileUploading: "آپلود ویدیو در حال انجام است.",
  playlist: "پلی‌لیست (اختیاری)",
  playlistCreate: "+ ایجاد پلی‌لیست",
  playlistEmpty: "هیچ پلی‌لیستی وجود ندارد.",
  playlistError: "خطا در دریافت پلی‌لیست‌ها",
  playlistLoading: "در حال بارگذاری پلی‌لیست‌ها...",
  playlistSearch: "جستجوی پلی‌لیست...",
  playlistTitle: "پلی‌لیست",
  publish: "انتشار ویدیو",
  publishLoading: "در حال آپلود...",
  publicDescription: "در صورت فعال بودن، ویدیو برای همه کاربران قابل مشاهده است",
  publicShow: "نمایش عمومی ویدیو",
  rulesPrefix: "لطفا پیش از بارگذاری ویدیو",
  rulesTitle: "قوانین اربعین تی وی",
  rulesSuffix: "را مطالعه کنید",
  selectFile: "ابتدا فایل ویدیو را انتخاب کنید.",
  title: "عنوان ویدیو",
  titlePlaceholder: "عنوان ویدیو را وارد کنید",
  uploadFile: "آپلود فایل",
  urlReady: "لینک ویدیو آماده ثبت است.",
  urlReadyPlatform: "لینک ویدیو وارد شده است.",
  videoLink: "لینک ویدیو",
  validationCover: "لطفاً یک تصویر کاور انتخاب کنید",
  validationTitle: "لطفاً عنوان ویدیو را وارد کنید",
  validationTitleChannel: "لطفاً عنوان و کانال را کامل کنید",
  validationVideo: "لطفاً ویدیو آپلود کنید یا لینک وارد کنید",
};